services:
  - type: web
    name: agriculture-tech
    env: python
    buildCommand: chmod +x build-simple.sh && ./build-simple.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 